[workspace]
members = ["ahci","framebuffer", "eucalypt_fs", "ide", "pci", "kernel", "bare_x86_64", "process", "sched", "memory", "usb", "syscall"]
resolver = "2"

[profile.dev]
opt-level = 1

[workspace.dependencies]
# External Dependencies
x86_64 = "0.15.2"
limine = "0.5.0"
uart_16550 = "0.4.0"
spin = "0.10.0"

# Eucalypt crates
ahci =        { path = "./ahci" }
framebuffer = { path = "./framebuffer" }
ide =         { path = "./ide" }
pci =         { path = "./pci" }
bare_x86_64 = { path = "./bare_x86_64" }
eucalypt_fs = { path = "./eucalypt_fs" }
sched =       { path = "./sched" }
process =     { path = "./process" }
memory =      { path = "./memory" }
usb =         { path = "./usb" }
syscall =     { path = "./syscall"}